name: Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --prod

      - name: Deploy to Azure Blob Storage
        run: |
          az storage blob upload-batch -d csb100320029c4ba133 -s ./dist --connection-string "DefaultEndpointsProtocol=https;AccountName=csb100320029c4ba133;AccountKey=C+Jkg2TrVZNkv7SQzJTjYIfQDBuTeb71DMvAoQCpd69hS0Tqj8etokuWix4OgfiYvL4Ed2ieLk4L+AStqCLGrA==;EndpointSuffix=core.windows.net"
        env:
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}